parameters:
    facade.updates.class: SecretBase\AppBundle\Services\Facade\Updates
    facade.upload.class: SecretBase\AppBundle\Services\Facade\Upload

services:
    facade.updates:
        class: %facade.updates.class%
        arguments: ["@media.manager.album", "@media.manager.photo"]

    facade.upload:
        class: %facade.upload.class%
        arguments: ["@media.manager.album", "@media.manager.photo"]
