parameters:
    facade.status.class: SecretBase\AppBundle\Services\Facade\Status
    facade.upload.class: SecretBase\AppBundle\Services\Facade\Upload

services:
    facade.status:
        class: %facade.status.class%
        arguments: [@media.manager.album, @media.manager.image, @storage.manager]

    facade.upload:
        class: %facade.upload.class%
        arguments: [@media.manager.album, @media.manager.image]
