parameters:
    media_manager.class: SecretBase\AppBundle\Services\Manager\MediaManager
    album_manager.class: SecretBase\AppBundle\Services\Manager\AlbumManager
    group_manager.class: SecretBase\AppBundle\Services\Manager\GroupManager
    user_manager.class: SecretBase\AppBundle\Services\Manager\UserManager
    status_manager.class: SecretBase\AppBundle\Services\Manager\StatusManager
    following_manager.class: SecretBase\AppBundle\Services\Manager\FollowingManager

services:
    user_manager:
        class: '%user_manager.class%'
        arguments: ["@doctrine.orm.entity_manager", "@fos_user.user_manager"]

    album_manager:
        class: '%album_manager.class%'
        arguments: ["@doctrine.orm.entity_manager", "@media_manager"]

    media_manager:
        class: '%media_manager.class%'
        arguments: ["@doctrine.orm.entity_manager", "@sonata.media.manager.media", "@sonata.media.pool"]

    group_manager:
        class: '%group_manager.class%'
        arguments: ["@doctrine.orm.entity_manager"]

    status_manager:
        class: '%status_manager.class%'
        arguments: ["@elasticsearch"]

    following_manager:
        class: '%following_manager.class%'
        arguments: ["@doctrine.orm.entity_manager"]