home_page:
    type: rest
    resource: SecretBase\AppBundle\Controller\DefaultController
updates:
    type: rest
    resource: SecretBase\AppBundle\Controller\StatusController
user:
    type: rest
    resource: SecretBase\AppBundle\Controller\UserController
registration:
    type: rest
    resource: SecretBase\AppBundle\Controller\RegistrationController
following:
    type: rest
    resource: SecretBase\AppBundle\Controller\FollowingController
lobby:
    type: rest
    resource: SecretBase\AppBundle\Controller\LobbyController
gallery:
    type: rest
    resource: SecretBase\AppBundle\Controller\GalleryController
