home_page:
    type: rest
    resource: SecretBase\AppBundle\Controller\DefaultController
status:
    type: rest
    resource: SecretBase\AppBundle\Controller\StatusController
image:
    type: rest
    resource: SecretBase\AppBundle\Controller\ImageController

user:
    type: rest
    resource: SecretBase\AppBundle\Controller\UserController

registration:
    type: rest
    resource: SecretBase\AppBundle\Controller\RegistrationController
