home_page:
    type: rest
    resource: SecretBase\AppBundle\Controller\DefaultController
updates:
    type: rest
    resource: SecretBase\AppBundle\Controller\UpdatesController
user:
    type: rest
    resource: SecretBase\AppBundle\Controller\UserController

registration:
    type: rest
    resource: SecretBase\AppBundle\Controller\RegistrationController
