imports:
    - { resource: manager.yml }
    - { resource: facade.yml }
    - { resource: storage.yml }

services:
    successful.logout.handler:
        class: SecretBase\AppBundle\Listener\SuccessfulLogoutHandler