imports:
    - { resource: manager.yml }
    - { resource: storage.yml }
    - { resource: mailer.yml }

parameters:
    successful_logout_handler.class: SecretBase\AppBundle\Listener\SuccessfulLogoutHandler
    status_handler.class: SecretBase\AppBundle\Services\StatusHandler
    user_profile_handler.class: SecretBase\AppBundle\Services\UserProfileHandler
    user_registration_handler.class: SecretBase\AppBundle\Services\UserRegistrationHandler

services:
    successful_logout_handler:
        class: '%successful_logout_handler.class%'

    status_handler:
        class: '%status_handler.class%'
        arguments: ["@media_manager", "@album_manager", "@elasticsearch"]

    user_profile_handler:
        class: '%user_profile_handler.class%'
        arguments: ["@media_manager", "@album_manager", "@user_manager"]

    user_registration_handler:
        class: '%user_registration_handler.class%'
        arguments: ["@user_manager", "@group_manager"]