parameters:
    storage_adapter.elasticsearch.class: SecretBase\AppBundle\Services\Storage\Adapter\ElasticsearchStorageAdapter

services:
    storage_adapter.elasticsearch:
        class: '%storage_adapter.elasticsearch.class%'
        tags:
            - {name: storage, alias: elasticsearch}