parameters:
    elastica.class: SecretBase\AppBundle\Services\NoSQLStorage\Elasticsearch

services:
    elasticsearch:
        class: '%elastica.class%'
        arguments: [{host: '%es_server%', port: '%es_server_port%'}]
        calls:
            - [setIndex, ["%es_index%"]]