parameters:
    elasticsearch.class: SecretBase\AppBundle\Services\NoSQLStorage\Elasticsearch

services:
    elasticsearch:
        class: '%elasticsearch.class%'
        arguments: ["%es_server%", "%es_index%", "%es_type%"]