fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sonata_media:
    resource: "@SonataMediaBundle/Resources/config/routing/media.xml"

secret_base:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /