fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sonata_media:
    path: /media/view/{id}/{format}
    defaults: { _controller: 'SonataMediaBundle:Media:view', format: reference }

secret_base:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /