registration:
    resource: "@RegistrationBundle/Resources/config/routing.yml"
    prefix:   /

authentication:
    resource: "@AuthenticationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
